import "pkg:/components/parts/AutoBind/OnNodeReadyNoOp.bs"
import "pkg:/source/utils/FocusManagement.bs"
import "pkg:/source/utils/Types.bs"

function Init()
    m.top.focusable = true
    m.top.itemSpacings = [8]

    m.button = m.top.findNode("button")
    m.button.observeField("buttonSelected", FuncName(OpenPlaybackSpeedSelector))
    AdjustButtonLabel(m.button)
end function

function OnFocusChange() as void
    if m.top.focus
        NodeSetFocus(m.button, true)
    end if
end function

function AdjustButtonLabel(button as object) as void
    for each child in button.getChildren(-1, 0)
        if child.isSubtype("Label") and child.hasField("horizAlign")
            child.observeField("horizAlign", FuncName(OnButtonLabelHorizAlignChanged))
            child.horizAlign = "left"
            return
        end if
    end for
end function

function OnButtonLabelHorizAlignChanged(event as object) as void
    label = event.getRoSGNode()
    if label.horizAlign <> "left"
        label.horizAlign = "left"
    end if
end function

function BindPreference(preferences as object, key as string) as void
    if m.preferences <> invalid and m.key <> invalid
        m.preferences.unobserveFieldScoped(m.key)
    end if

    m.preferences = preferences
    m.key = key

    if preferences <> invalid and key <> invalid
        preferences.observeFieldScoped(key, FuncName(OnPreferenceChange))
        OnPreferenceChange()
    end if
end function

function OpenPlaybackSpeedSelector() as void
    selector = CreateObject("roSGNode", "PlaybackSpeedSelector")
    m.appController@.PushScreen(selector)
    selector@.BindNode()
    selector.options = m.top.options
    selector.value = m.top.value
    selector.observeField("save", FuncName(OnSavePlaybackSpeedSelector))
end function

function OnSavePlaybackSpeedSelector(event as object) as void
    selector = event.GetRoSGNode()
    m.top.value = selector.value
end function

function OnPreferenceChange() as void
    m.top.value = m.preferences[m.key]
end function

function OnOptionsChange() as void
    OnValueChange()
end function

function OnValueChange() as void
    value = ValidString(m.top.value)
    label = value + "x"

    for each option in m.top.options
        if option.value = value
            label = Tr(option.displayText)
            exit for
        end if
    end for
    m.button.text = label

    if m.preferences <> invalid and m.key <> invalid
        m.preferences[m.key] = value
    end if
end function
